### ISSUE TITLE
Property Resolver Source Path

### ISSUE THREAD

**Issue by jonasheinisch** [ForgeRock/forgeops#119]
I am trying to use docker images for local testing purpose. When building the docker image from repo as well as pulling the evaluation images from bintray, I get the following exception when I try to run the container:

```
Exception in thread "main" java.lang.IllegalArgumentException: Property resolver source path does not exist: /var/run/openidm 
at org.forgerock.config.resolvers.PropertyResolvers.resolverForPath(PropertyResolvers.java:284) 
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) 
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) 
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) 
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) 
at org.forgerock.config.resolvers.PropertyResolvers.bootstrapPropertyResolver(PropertyResolvers.java:115) 
at org.forgerock.openidm.launcher.OSGiFrameworkService.init(OSGiFrameworkService.java:338) 
at org.forgerock.openidm.launcher.OSGiFrameworkService.init(OSGiFrameworkService.java:318) 
at org.forgerock.openidm.launcher.Main.main(Main.java:44)
```

**Comment by wstrange** [comment]
Hi Jonas

The docker image needs several volumes mounted to function properly. The helm chart for openidm will do this. I assume you are trying to run just vanillia docker?

We are working on a better developer workflow - probably using something like skaffold. But it willl still require some Kubernetes environment (minikube, GKE, EKS, etc.)

**Comment by wstrange** [comment]
If you still have issue using Helm, please reopen.
