### ISSUE TITLE
Forgeops Info / Python Issues 3.12 / Mac

### ISSUE THREAD

**Issue by nickehunt** [ForgeRock/forgeops#682]
Recently I did a brew upgrade and looks like forgeops utils are erroring when trying to run.  When trying to run any version / branch of forgeops, I receive the error messages below.  Anyone have similar issues / install command that can be used?

`Traceback (most recent call last):
  File "/Users/nickehunt/Documents/Projects/forgerock/environments/fomkdev/forgeops/bin/./config", line 11, in <module>
    import utils
  File "/Users/nickehunt/Documents/Projects/forgerock/environments/fomkdev/forgeops/bin/utils.py", line 16, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'`

**Comment by nickehunt** [comment]
I fixed this issue (if anyone has it)....you can re-install the pkg_resources with the below command for python3.12 which is not available by default.

brew install python-setuptools

Nick
